"""create_orbital_guard_tables

Revision ID: 901b78297284
Revises: 
Create Date: 2026-09-26 22:19:05.287629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '901b78297284'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('satellites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('norad_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('international_designator', sa.String(length=64), nullable=True),
    sa.Column('object_type', sa.String(length=64), nullable=False),
    sa.Column('country_owner', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('satellites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_satellites_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_satellites_norad_id'), ['norad_id'], unique=True)

    op.create_table('conjunction_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('primary_satellite_id', sa.Integer(), nullable=False),
    sa.Column('secondary_satellite_id', sa.Integer(), nullable=False),
    sa.Column('tca', sa.DateTime(timezone=True), nullable=False),
    sa.Column('miss_distance_km', sa.Float(), nullable=False),
    sa.Column('relative_velocity_kms', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('calculation_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['primary_satellite_id'], ['satellites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['secondary_satellite_id'], ['satellites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conjunction_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conjunction_events_primary_satellite_id'), ['primary_satellite_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conjunction_events_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_conjunction_events_secondary_satellite_id'), ['secondary_satellite_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conjunction_events_tca'), ['tca'], unique=False)

    op.create_table('orbital_elements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('satellite_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('epoch', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tle_line1', sa.String(length=128), nullable=True),
    sa.Column('tle_line2', sa.String(length=128), nullable=True),
    sa.Column('mean_motion', sa.Float(), nullable=False),
    sa.Column('eccentricity', sa.Float(), nullable=False),
    sa.Column('inclination', sa.Float(), nullable=False),
    sa.Column('ra_of_asc_node', sa.Float(), nullable=False),
    sa.Column('arg_of_pericenter', sa.Float(), nullable=False),
    sa.Column('mean_anomaly', sa.Float(), nullable=False),
    sa.Column('bstar', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['satellite_id'], ['satellites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orbital_elements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orbital_elements_epoch'), ['epoch'], unique=False)
        batch_op.create_index('ix_orbital_elements_sat_epoch', ['satellite_id', 'epoch'], unique=False)
        batch_op.create_index(batch_op.f('ix_orbital_elements_satellite_id'), ['satellite_id'], unique=False)

    op.create_table('orbital_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('satellite_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('frame', sa.String(length=32), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('z', sa.Float(), nullable=False),
    sa.Column('vx', sa.Float(), nullable=False),
    sa.Column('vy', sa.Float(), nullable=False),
    sa.Column('vz', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude_km', sa.Float(), nullable=False),
    sa.Column('speed_kms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['satellite_id'], ['satellites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orbital_states', schema=None) as batch_op:
        batch_op.create_index('ix_orbital_states_sat_ts', ['satellite_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_orbital_states_satellite_id'), ['satellite_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orbital_states_timestamp'), ['timestamp'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('conjunction_id', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conjunction_id'], ['conjunction_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_conjunction_id'), ['conjunction_id'], unique=False)

    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conjunction_id', sa.String(length=64), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('scoring_method', sa.String(length=64), nullable=False),
    sa.Column('features_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conjunction_id'], ['conjunction_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_assessments_conjunction_id'), ['conjunction_id'], unique=False)

    op.create_table('simulation_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conjunction_id', sa.String(length=64), nullable=False),
    sa.Column('delta_v_mps', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=32), nullable=False),
    sa.Column('lead_time_hours', sa.Float(), nullable=False),
    sa.Column('baseline_miss_distance_km', sa.Float(), nullable=False),
    sa.Column('simulated_miss_distance_km', sa.Float(), nullable=False),
    sa.Column('baseline_risk_score', sa.Float(), nullable=False),
    sa.Column('simulated_risk_score', sa.Float(), nullable=False),
    sa.Column('risk_reduction_percent', sa.Float(), nullable=False),
    sa.Column('simulation_method', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conjunction_id'], ['conjunction_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulation_runs_conjunction_id'), ['conjunction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulation_runs_conjunction_id'))

    op.drop_table('simulation_runs')
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_assessments_conjunction_id'))

    op.drop_table('risk_assessments')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_conjunction_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('orbital_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orbital_states_timestamp'))
        batch_op.drop_index(batch_op.f('ix_orbital_states_satellite_id'))
        batch_op.drop_index('ix_orbital_states_sat_ts')

    op.drop_table('orbital_states')
    with op.batch_alter_table('orbital_elements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orbital_elements_satellite_id'))
        batch_op.drop_index('ix_orbital_elements_sat_epoch')
        batch_op.drop_index(batch_op.f('ix_orbital_elements_epoch'))

    op.drop_table('orbital_elements')
    with op.batch_alter_table('conjunction_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conjunction_events_tca'))
        batch_op.drop_index(batch_op.f('ix_conjunction_events_secondary_satellite_id'))
        batch_op.drop_index(batch_op.f('ix_conjunction_events_risk_level'))
        batch_op.drop_index(batch_op.f('ix_conjunction_events_primary_satellite_id'))

    op.drop_table('conjunction_events')
    with op.batch_alter_table('satellites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_satellites_norad_id'))
        batch_op.drop_index(batch_op.f('ix_satellites_name'))

    op.drop_table('satellites')
    # ### end Alembic commands ###
